In [1]:
#importing the pandas and numpy libraries
import pandas as pd
import numpy as np

In [3]:
#loading dataset
from sklearn.datasets import load_breast_cancer
data=load_breast_cancer()

In [4]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [5]:
#there are 30 feature columns
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [6]:
#and there is one target column
data.target
#catagorical data where 1=bening tumor and 0 = malignant tumor

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [7]:
data.target_names

array(['malignant', 'benign'], dtype='<U9')

Now this is a datadet after reviewing its features and target, we have to convert to dataframe in order to perform preprocessing and the splitting of the dataset


# Loading the  dataset

In [8]:
df=pd.DataFrame(np.c_[data.data,data.target],columns=[list(data.feature_names)+['target']])

In [9]:
df.head(10)

mean radius mean texture mean perimeter mean area mean smoothness  \
0       17.99        10.38         122.80    1001.0         0.11840   
1       20.57        17.77         132.90    1326.0         0.08474   
2       19.69        21.25         130.00    1203.0         0.10960   
3       11.42        20.38          77.58     386.1         0.14250   
4       20.29        14.34         135.10    1297.0         0.10030   
5       12.45        15.70          82.57     477.1         0.12780   
6       18.25        19.98         119.60    1040.0         0.09463   
7       13.71        20.83          90.20     577.9         0.11890   
8       13.00        21.82          87.50     519.8         0.12730   
9       12.46        24.04          83.97     475.9         0.11860   

  mean compactness mean concavity mean concave points mean symmetry  \
0          0.27760        0.30010             0.14710        0.2419   
1          0.07864        0.08690             0.07017        0.1812   
2          0.15990        0.19740             0.12790        0.2069   
3          0.28390        0.24140             0.10520        0.2597   
4          0.13280        0.19800             0.10430        0.1809   
5          0.17000        0.15780             0.08089        0.2087   
6          0.10900        0.11270             0.07400        0.1794   
7          0.16450        0.09366             0.05985        0.2196   
8          0.19320        0.18590             0.09353        0.2350   
9          0.23960        0.22730             0.08543        0.2030   

  mean fractal dimension  ... worst texture worst perimeter worst area  \
0                0.07871  ...         17.33          184.60     2019.0   
1                0.05667  ...         23.41          158.80     1956.0   
2                0.05999  ...         25.53          152.50     1709.0   
3                0.09744  ...         26.50           98.87      567.7   
4                0.05883  ...         16.67          152.20     1575.0   
5                0.07613  ...         23.75          103.40      741.6   
6                0.05742  ...         27.66          153.20     1606.0   
7                0.07451  ...         28.14          110.60      897.0   
8                0.07389  ...         30.73          106.20      739.3   
9                0.08243  ...         40.68           97.65      711.4   

  worst smoothness worst compactness worst concavity worst concave points  \
0           0.1622            0.6656          0.7119               0.2654   
1           0.1238            0.1866          0.2416               0.1860   
2           0.1444            0.4245          0.4504               0.2430   
3           0.2098            0.8663          0.6869               0.2575   
4           0.1374            0.2050          0.4000               0.1625   
5           0.1791            0.5249          0.5355               0.1741   
6           0.1442            0.2576          0.3784               0.1932   
7           0.1654            0.3682          0.2678               0.1556   
8           0.1703            0.5401          0.5390               0.2060   
9           0.1853            1.0580          1.1050               0.2210   

  worst symmetry worst fractal dimension target  
0         0.4601                 0.11890    0.0  
1         0.2750                 0.08902    0.0  
2         0.3613                 0.08758    0.0  
3         0.6638                 0.17300    0.0  
4         0.2364                 0.07678    0.0  
5         0.3985                 0.12440    0.0  
6         0.3063                 0.08368    0.0  
7         0.3196                 0.11510    0.0  
8         0.4378                 0.10720    0.0  
9         0.4366                 0.20750    0.0  

[10 rows x 31 columns]

In [10]:
df.tail()

mean radius mean texture mean perimeter mean area mean smoothness  \
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst texture worst perimeter worst area  \
564                0.05623  ...         26.40          166.10     2027.0   
565                0.05533  ...         38.25          155.00     1731.0   
566                0.05648  ...         34.12          126.70     1124.0   
567                0.07016  ...         39.42          184.60     1821.0   
568                0.05884  ...         30.37           59.16      268.6   

    worst smoothness worst compactness worst concavity worst concave points  \
564          0.14100           0.21130          0.4107               0.2216   
565          0.11660           0.19220          0.3215               0.1628   
566          0.11390           0.30940          0.3403               0.1418   
567          0.16500           0.86810          0.9387               0.2650   
568          0.08996           0.06444          0.0000               0.0000   

    worst symmetry worst fractal dimension target  
564         0.2060                 0.07115    0.0  
565         0.2572                 0.06637    0.0  
566         0.2218                 0.07820    0.0  
567         0.4087                 0.12400    0.0  
568         0.2871                 0.07039    1.0  

[5 rows x 31 columns]

In [11]:
df.shape

(569, 31)

In [12]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

# Spliting of the dataset into features and labels

In [13]:
features=df.iloc[:,0:-1]
label=df.iloc[:,-1]

In [14]:
features

mean radius mean texture mean perimeter mean area mean smoothness  \
0         17.99        10.38         122.80    1001.0         0.11840   
1         20.57        17.77         132.90    1326.0         0.08474   
2         19.69        21.25         130.00    1203.0         0.10960   
3         11.42        20.38          77.58     386.1         0.14250   
4         20.29        14.34         135.10    1297.0         0.10030   
..          ...          ...            ...       ...             ...   
564       21.56        22.39         142.00    1479.0         0.11100   
565       20.13        28.25         131.20    1261.0         0.09780   
566       16.60        28.08         108.30     858.1         0.08455   
567       20.60        29.33         140.10    1265.0         0.11780   
568        7.76        24.54          47.92     181.0         0.05263   

    mean compactness mean concavity mean concave points mean symmetry  \
0            0.27760        0.30010             0.14710        0.2419   
1            0.07864        0.08690             0.07017        0.1812   
2            0.15990        0.19740             0.12790        0.2069   
3            0.28390        0.24140             0.10520        0.2597   
4            0.13280        0.19800             0.10430        0.1809   
..               ...            ...                 ...           ...   
564          0.11590        0.24390             0.13890        0.1726   
565          0.10340        0.14400             0.09791        0.1752   
566          0.10230        0.09251             0.05302        0.1590   
567          0.27700        0.35140             0.15200        0.2397   
568          0.04362        0.00000             0.00000        0.1587   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
0                  0.07871  ...       25.380         17.33          184.60   
1                  0.05667  ...       24.990         23.41          158.80   
2                  0.05999  ...       23.570         25.53          152.50   
3                  0.09744  ...       14.910         26.50           98.87   
4                  0.05883  ...       22.540         16.67          152.20   
..                     ...  ...          ...           ...             ...   
564                0.05623  ...       25.450         26.40          166.10   
565                0.05533  ...       23.690         38.25          155.00   
566                0.05648  ...       18.980         34.12          126.70   
567                0.07016  ...       25.740         39.42          184.60   
568                0.05884  ...        9.456         30.37           59.16   

    worst area worst smoothness worst compactness worst concavity  \
0       2019.0          0.16220           0.66560          0.7119   
1       1956.0          0.12380           0.18660          0.2416   
2       1709.0          0.14440           0.42450          0.4504   
3        567.7          0.20980           0.86630          0.6869   
4       1575.0          0.13740           0.20500          0.4000   
..         ...              ...               ...             ...   
564     2027.0          0.14100           0.21130          0.4107   
565     1731.0          0.11660           0.19220          0.3215   
566     1124.0          0.11390           0.30940          0.3403   
567     1821.0          0.16500           0.86810          0.9387   
568      268.6          0.08996           0.06444          0.0000   

    worst concave points worst symmetry worst fractal dimension  
0                 0.2654         0.4601                 0.11890  
1                 0.1860         0.2750                 0.08902  
2                 0.2430         0.3613                 0.08758  
3                 0.2575         0.6638                 0.17300  
4                 0.1625         0.2364                 0.07678  
..                   ...            ...                     ...  
564               0.22

In [15]:
label

0      0.0
1      0.0
2      0.0
3      0.0
4      0.0
      ... 
564    0.0
565    0.0
566    0.0
567    0.0
568    1.0
Name: (target,), Length: 569, dtype: float64

# Splitting the dataset into training and testing dataset

In [16]:
from sklearn.model_selection import train_test_split
f_train,f_test,l_train,l_test= train_test_split(features,label,test_size=0.3,random_state=2020)


In [22]:
f_train


mean radius mean texture mean perimeter mean area mean smoothness  \
293       11.85        17.46          75.54     432.7         0.08372   
299       10.51        23.09          66.85     334.2         0.10150   
194       14.86        23.21         100.40     671.4         0.10440   
405       10.94        18.59          70.39     370.0         0.10040   
410       11.36        17.57          72.49     399.8         0.08858   
..          ...          ...            ...       ...             ...   
560       14.05        27.15          91.38     600.4         0.09929   
157       16.84        19.46         108.40     880.2         0.07445   
91        15.37        22.76         100.20     728.2         0.09200   
323       20.34        21.51         135.90    1264.0         0.11700   
392       15.49        19.97         102.40     744.7         0.11600   

    mean compactness mean concavity mean concave points mean symmetry  \
293          0.05642        0.02688             0.02280        0.1875   
299          0.06797        0.02495             0.01875        0.1695   
194          0.19800        0.16970             0.08878        0.1737   
405          0.07460        0.04944             0.02932        0.1486   
410          0.05313        0.02783             0.02100        0.1601   
..               ...            ...                 ...           ...   
560          0.11260        0.04462             0.04304        0.1537   
157          0.07223        0.05150             0.02771        0.1844   
91           0.10360        0.11220             0.07483        0.1717   
323          0.18750        0.25650             0.15040        0.2569   
392          0.15620        0.18910             0.09113        0.1929   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
293                0.05715  ...        13.06         25.75           84.35   
299                0.06556  ...        10.93         24.22           70.10   
194                0.06672  ...        16.08         27.78          118.60   
405                0.06615  ...        12.40         25.58           82.76   
410                0.05913  ...        13.05         36.32           85.07   
..                     ...  ...          ...           ...             ...   
560                0.06171  ...        15.30         33.17          100.20   
157                0.05268  ...        18.22         28.07          120.30   
91                 0.06097  ...        16.43         25.84          107.50   
323                0.06670  ...        25.30         31.86          171.10   
392                0.06744  ...        21.20         29.41          142.10   

    worst area worst smoothness worst compactness worst concavity  \
293      517.8          0.13690           0.17580         0.13160   
299      362.7          0.11430           0.08614         0.04158   
194      784.7          0.13160           0.46480         0.45890   
405      472.4          0.13630           0.16440         0.14120   
410      521.3          0.14530           0.16220         0.18110   
..         ...              ...               ...             ...   
560      706.7          0.12410           0.22640         0.13260   
157     1032.0          0.08774           0.17100         0.18820   
91       830.9          0.12570           0.19970         0.28460   
323     1938.0          0.15920           0.44920         0.53440   
392     1359.0          0.16810           0.39130         0.55530   

    worst concave points worst symmetry worst fractal dimension  
293              0.09140         0.3101                 0.07007  
299              0.03125         0.2227                 0.06777  
194              0.17270         0.3000                 0.08701  
405              0.07887         0.2251                 0.07732  
410              0.08698         0.2973                 0.07745  
..                   ...            ...                     ...  
560              0.104

In [18]:
f_test

mean radius mean texture mean perimeter mean area mean smoothness  \
236       23.21        26.97         153.50    1670.0         0.09509   
106       11.64        18.33          75.17     412.5         0.11420   
284       12.89        15.70          84.08     516.6         0.07818   
262       17.29        22.13         114.40     947.8         0.08999   
356       13.05        18.59          85.09     512.0         0.10820   
..          ...          ...            ...       ...             ...   
389       19.55        23.21         128.90    1174.0         0.10100   
328       16.27        20.71         106.90     813.7         0.11690   
189       12.30        15.90          78.83     463.7         0.08080   
229       12.83        22.33          85.26     503.2         0.10880   
219       19.53        32.47         128.00    1223.0         0.08420   

    mean compactness mean concavity mean concave points mean symmetry  \
236          0.16820        0.19500             0.12370        0.1909   
106          0.10170        0.07070             0.03485        0.1801   
284          0.09580        0.11150             0.03390        0.1432   
262          0.12730        0.09697             0.07507        0.2108   
356          0.13040        0.09603             0.05603        0.2035   
..               ...            ...                 ...           ...   
389          0.13180        0.18560             0.10210        0.1989   
328          0.13190        0.14780             0.08488        0.1948   
189          0.07253        0.03844             0.01654        0.1667   
229          0.17990        0.16950             0.06861        0.2123   
219          0.11300        0.11450             0.06637        0.1428   

    mean fractal dimension  ... worst radius worst texture worst perimeter  \
236                0.06309  ...        31.01         34.51          206.00   
106                0.06520  ...        13.14         29.26           85.51   
284                0.05935  ...        13.90         19.69           92.12   
262                0.05464  ...        20.39         27.24          137.90   
356                0.06501  ...        14.19         24.85           94.22   
..                     ...  ...          ...           ...             ...   
389                0.05884  ...        20.82         30.44          142.00   
328                0.06277  ...        19.28         30.38          129.80   
189                0.05474  ...        13.35         19.59           86.65   
229                0.07254  ...        15.20         30.15          105.30   
219                0.05313  ...        27.90         45.41          180.20   

    worst area worst smoothness worst compactness worst concavity  \
236     2944.0          0.14810            0.4126          0.5820   
106      521.7          0.16880            0.2660          0.2873   
284      595.6          0.09926            0.2317          0.3344   
262     1295.0          0.11340            0.2867          0.2298   
356      591.2          0.13430            0.2658          0.2573   
..         ...              ...               ...             ...   
389     1313.0          0.12510            0.2414          0.3829   
328     1121.0          0.15900            0.2947          0.3597   
189      546.7          0.10960            0.1650          0.1423   
229      706.0          0.17770            0.5343          0.6282   
219     2477.0          0.14080            0.4097          0.3995   

    worst concave points worst symmetry worst fractal dimension  
236              0.25930         0.3103                 0.08677  
106              0.12180         0.2806                 0.09097  
284              0.10170         0.1999                 0.07127  
262              0.15280         0.3067                 0.07484  
356              0.12580         0.3113                 0.08317  
..                   ...            ...                     ...  
389              0.182

In [19]:
l_train

293    1.0
299    1.0
194    0.0
405    1.0
410    1.0
      ... 
560    1.0
157    1.0
91     0.0
323    0.0
392    0.0
Name: (target,), Length: 398, dtype: float64

In [20]:
l_test

236    0.0
106    1.0
284    1.0
262    0.0
356    1.0
      ... 
389    0.0
328    0.0
189    1.0
229    0.0
219    0.0
Name: (target,), Length: 171, dtype: float64

# Training the KNN classificastion Model

In [38]:
from sklearn.neighbors import KNeighborsClassifier

In [43]:
classifier=KNeighborsClassifier(n_neighbors=5)
classifier.fit(f_train,l_train)

KNeighborsClassifier()

# Testing the accuracy

In [44]:
classifier.score(f_test,l_test)

0.9239766081871345

# Predicting the result

In [31]:
patient1=[17.80,10.48,123.80,1011.0,0.11440,0.27860,0.30020,0.14710,0.2429,0.07831,17.23,180.60,2017.0,0.1632,0.6556,0.7120,0.2644,0.4620,0.11895,0.006193,25.38,17.33,184.6,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.1189]

In [32]:
p1=np.array([patient1])

In [33]:
p1

array([[1.7800e+01, 1.0480e+01, 1.2380e+02, 1.0110e+03, 1.1440e-01,
        2.7860e-01, 3.0020e-01, 1.4710e-01, 2.4290e-01, 7.8310e-02,
        1.7230e+01, 1.8060e+02, 2.0170e+03, 1.6320e-01, 6.5560e-01,
        7.1200e-01, 2.6440e-01, 4.6200e-01, 1.1895e-01, 6.1930e-03,
        2.5380e+01, 1.7330e+01, 1.8460e+02, 2.0190e+03, 1.6220e-01,
        6.6560e-01, 7.1190e-01, 2.6540e-01, 4.6010e-01, 1.1890e-01]])

In [47]:
classifier.predict(p1)

array([0.])

# DECISION TREE


In [48]:
from sklearn.tree import DecisionTreeClassifier

In [53]:
classifier_dt=DecisionTreeClassifier(criterion='gini')
#criterion is the function to measure the quality of the split it can be 'gini' or 'entropy'

In [54]:
classifier_dt.fit(f_train,l_train)

DecisionTreeClassifier()

# Evalution of the model by checking accuracy score

In [56]:
classifier_dt.score(f_test,l_test)

0.9590643274853801

In [68]:
classifier_dt.predict(p1)

array([0.])

# Checking the model when the criterion of entropy

In [57]:
classifier_dte=DecisionTreeClassifier(criterion='entropy')

In [60]:
classifier_dte.fit(f_train,l_train)

DecisionTreeClassifier(criterion='entropy')

In [61]:
classifier_dte.score(f_test,l_test)

0.9415204678362573

# Feature Scaling

In [62]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()

In [63]:
sc.fit(f_train)

StandardScaler()

In [64]:
f_train_sc=sc.transform(f_train)
f_test_sc=sc.transform(f_test)

In [65]:
classifier_sc=DecisionTreeClassifier(criterion='gini')


In [66]:
classifier_sc.fit(f_train_sc,l_train)

DecisionTreeClassifier()

In [67]:
classifier_sc.score(f_test_sc,l_test)

0.935672514619883

# Predicting Cancer

In [69]:
classifier_dt.predict(p1)

array([0.])

# Random  decision forest classifier

In [70]:
from sklearn.ensemble import RandomForestClassifier

In [71]:
classifier_rf=RandomForestClassifier(n_estimators=100)

In [73]:
classifier_rf.fit(f_train,l_train)

RandomForestClassifier()

In [74]:
classifier_rf.score(f_test,l_test)

0.9707602339181286

# predicting

In [75]:
classifier_rf.predict(p1)

array([0.])